networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:

services:
  pg:
    image: postgres:17.2
    container_name: pg
    environment:
      POSTGRES_DB: task_tracker
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "password"
    networks:
      - app-network
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d task_tracker"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: .
      dockerfile: backend/Backend.Dockerfile
    container_name: backend
    environment:
      DATABASE_URL: postgresql+asyncpg://user:password@pg:5432/task_tracker
      JWT_ALGORITHM: RS256
      JWT_EXPIRATION_MINUTES: 30
    networks:
      - app-network
    ports:
      - "8000:8000"
    depends_on:
      pg:
        condition: service_healthy
    restart: unless-stopped
    volumes:
      - ./backend:/app  # Для hot-reload в разработке
      - /app/__pycache__

  frontend:
    build:
      context: ./task-tracker-frontend
      dockerfile: Frontend.Dockerfile
      args:
        - REACT_APP_API_URL=https://t-track-api.avakov.netcraze.pro
    container_name: frontend
    environment:
      - CHOKIDAR_USEPOLLING=true  # Для hot-reload в Docker
      - WATCHPACK_POLLING=true    # Альтернатива для webpack
    networks:
      - app-network
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: unless-stopped
    volumes:
      - ./task-tracker-frontend:/app  # Для hot-reload
      - /app/node_modules              # Исключаем node_modules