networks:
  app-network:
    driver: bridge
  postgres:
    driver: bridge

services:
  pg:
    image: postgres:17.2
    container_name: pg
    environment:
      POSTGRES_DB: task_tracker
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "password"
    networks:
      - postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d miniapp_donates"]
      interval: 5s
      timeout: 5s
      retries: 5


volumes:
  postgres_data: