networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:

services:
  pg:
    image: postgres:17.2
    container_name: pg
    environment:
      POSTGRES_DB: task_tracker
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "password"
    networks:
      - app-network  # Подключаем к той же сети
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d task_tracker"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: task-tracker-backend
    environment:
      DATABASE_URL: postgresql+asyncpg://user:password@pg:5432/task_tracker  # Используем pg как hostname
      ALLOWED_ORIGINS: '["*"]'
      JWT_ALGORITHM: RS256
      JWT_EXPIRATION_MINUTES: 30
    networks:
      - app-network  # Та же сеть
    ports:
      - "8000:8000"
    depends_on:
      pg:
        condition: service_healthy
    restart: unless-stopped