"""edit_usergroups

Revision ID: 017a22c96aa3
Revises: dd774824053a
Create Date: 2026-04-22 13:27:27.941288

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '017a22c96aa3'
down_revision: Union[str, Sequence[str], None] = 'dd774824053a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_groups', sa.Column('joined_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_groups', 'joined_at')
    # ### end Alembic commands ###
