"""add_email_confirmations

Revision ID: 64a1b657ea7f
Revises: d4ad43db0221
Create Date: 2026-03-26 13:48:34.675261

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64a1b657ea7f'
down_revision: Union[str, Sequence[str], None] = 'd4ad43db0221'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_confirmations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_email_confirmations_expires_at', 'email_confirmations', ['expires_at'], unique=False)
    op.create_index(op.f('ix_email_confirmations_token'), 'email_confirmations', ['token'], unique=True)
    op.create_index(op.f('ix_email_confirmations_user_id'), 'email_confirmations', ['user_id'], unique=False)
    op.create_unique_constraint(None, 'users', ['phone'])
    op.create_unique_constraint(None, 'users', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_index(op.f('ix_email_confirmations_user_id'), table_name='email_confirmations')
    op.drop_index(op.f('ix_email_confirmations_token'), table_name='email_confirmations')
    op.drop_index('ix_email_confirmations_expires_at', table_name='email_confirmations')
    op.drop_table('email_confirmations')
    # ### end Alembic commands ###
