"""edit_groups

Revision ID: dd774824053a
Revises: bbe353b5df37
Create Date: 2026-04-22 13:19:44.094812

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd774824053a'
down_revision: Union[str, Sequence[str], None] = 'bbe353b5df37'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groups', sa.Column('icon', sa.String(), nullable=True))
    op.add_column('invitations', sa.Column('message', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invitations', 'message')
    op.drop_column('groups', 'icon')
    # ### end Alembic commands ###
